"""Markdown and TXT snapshot exporters (they render the same sections as the screen)."""

from __future__ import annotations

import os
from pathlib import Path
from typing import List, Optional, Tuple

from . import __app_name__, __version__
from .formatting import Section, build_sections, public_sections
from .system import Snapshot

TITLE = f"{__app_name__} \u2014 System Snapshot"


def _export_sections(snapshot: Snapshot) -> List[Section]:
    """Exports contain PUBLIC values only."""
    return public_sections(build_sections(snapshot))


def default_filename(snapshot: Snapshot, extension: str) -> str:
    return f"whosup-{snapshot.timestamp:%Y-%m-%d-%H%M%S}.{extension}"


def _escape_md(text: str) -> str:
    return text.replace("|", "\\|")


def to_markdown(snapshot: Snapshot) -> str:
    out: List[str] = [f"# {TITLE}", "", f"**Date:** {snapshot.timestamp:%Y-%m-%d %H:%M:%S}", ""]
    for section in _export_sections(snapshot):
        out.append(f"## {section.title.title()}")
        out.append("")
        for row in section.rows:
            out.append(f"* {row.label}: {row.value}")
        for line in section.lines:
            out.append(f"* {line}")
        if section.table_rows:
            out.append("| " + " | ".join(section.table_header) + " |")
            out.append("| " + " | ".join(["---"] + ["---:"] * (len(section.table_header) - 1)) + " |")
            for cells in section.table_rows:
                out.append("| " + " | ".join(_escape_md(c) for c in cells) + " |")
        out.append("")
    out.append(f"*Generated by {__app_name__} v{__version__}*")
    return "\n".join(out) + "\n"


def _text_table(header: Tuple[str, ...], rows: List[Tuple[str, ...]]) -> List[str]:
    widths = [max(len(str(cell)) for cell in column) for column in zip(header, *rows)]
    def fmt(cells: Tuple[str, ...]) -> str:
        first = cells[0].ljust(widths[0])
        rest = [cell.rjust(width) for cell, width in zip(cells[1:], widths[1:])]
        return "  ".join([first] + rest)
    return [fmt(header)] + [fmt(row) for row in rows]


def _text_section(section: Section) -> List[str]:
    out = [section.title, "-" * len(section.title)]
    if section.rows:
        width = max(len(row.label) for row in section.rows) + 2
        out.extend(f"{row.label + ':':<{width}}{row.value}" for row in section.rows)
    out.extend(section.lines)
    if section.table_rows:
        out.extend(_text_table(section.table_header, section.table_rows))
    return out


def to_text(snapshot: Snapshot) -> str:
    out: List[str] = [TITLE, f"Date: {snapshot.timestamp:%Y-%m-%d %H:%M:%S}", ""]
    for section in _export_sections(snapshot):
        out.extend(_text_section(section))
        out.append("")
    out.append(f"{__app_name__} v{__version__}")
    return "\n".join(out) + "\n"


def write_export(snapshot: Snapshot, fmt: str, output: Optional[str] = None) -> Path:
    """Write one snapshot to disk. fmt is 'md' or 'txt'."""
    if fmt not in ("md", "txt"):
        raise ValueError(f"Unsupported export format: {fmt}")
    path = Path(output) if output else Path(default_filename(snapshot, fmt))
    content = to_markdown(snapshot) if fmt == "md" else to_text(snapshot)
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)  # owner-only for new files
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        handle.write(content)
    return path
